Allow to declare quantity and cursor when retrieving broadcaster's subscribers
TwitchLib/TwitchLib.Api pull request #153
Opened 2020-09-08 20:39 UTC by pietrodicaprio

This change allows declaring a quantity (`first`) of subscribers to retrieve and the `cursor` when calling `GetBroadcasterSubscriptions`

2020-09-12 17:08 UTC, Syzuna requested changes

2020-09-12 17:08 UTC, Syzuna commented on TwitchLib.Api.Helix/TwitchLib.Api.Helix.csproj
> +    <Version>3.2.1-SP</Version>
Please dont change around the version

2020-09-12 17:08 UTC, Syzuna commented on TwitchLib.Api.Helix/TwitchLib.Api.Helix.csproj
> +    <AssemblyVersion>3.2.1</AssemblyVersion>
Please dont change around the version

2020-09-12 17:08 UTC, Syzuna commented on TwitchLib.Api.Helix/TwitchLib.Api.Helix.csproj
> +    <FileVersion>3.2.1</FileVersion>
Please dont change around the version

2020-09-12 17:08 UTC, Syzuna commented on TwitchLib.Api.Helix/Subscriptions.cs
> +        public Task<GetBroadcasterSubscriptionsResponse> GetBroadcasterSubscriptions(string broadcasterId, string cursor = null,
to keep things consistent I would like to have quantity changed to first as variable name

2020-09-14 16:45 UTC, Syzuna commented
also please dont PR against the master branch.
use the dev branch instead

2020-09-14 20:21 UTC, pietrodicaprio reviewed
Got it. Sorry for the version naming, initially was not meant for a PR but then I said "why not?".
Going to take care for sure for any new change I do

2020-11-09 22:57 UTC, Syzuna commented
LGTM. will merge.

Thanks and sorry for keeping you waiting.
The last months were kind of a ride and its still ongoing.

2020-11-09 22:57 UTC, Syzuna approved these changes

2020-11-09 22:57 UTC, merged