Conduit support
TwitchLib/TwitchLib.Api pull request #389
Opened 2024-04-01 15:37 UTC by swiftyspiffy

Adds new methods for Helix/EventSub:
- GetConduits
- CreateConduit
- UpdateConduit
- DeleteConduit
- GetConduitShards
- UpdateConduitShards

Tested:
- Creating conduits
- Getting conduits
- Deleting conduits
- Updating conduit with 2 shards, one for webhook and one for websocket
- Getting conduit shard statuses

2024-04-01 15:57 UTC, Mahsaap approved these changes

2024-04-01 16:59 UTC, AoshiW requested changes

2024-04-01 16:59 UTC, AoshiW commented on TwitchLib.Api.Helix/EventSub.cs
> +            if (request.ShardCount is <= 0 or > 20_0000)
```suggestion
            if (request.ShardCount is <= 0 or > 20_000)
```

2024-04-01 16:59 UTC, AoshiW commented on TwitchLib.Api.Helix/EventSub.cs
> +            if (request.ShardCount is <= 0 or > 20_0000)
```suggestion
            if (request.ShardCount is <= 0 or > 20_000)
```

2024-04-02 11:47 UTC, swiftyspiffy commented on TwitchLib.Api.Helix/EventSub.cs
> +            if (request.ShardCount is <= 0 or > 20_0000)
good catch

2024-04-02 11:47 UTC, swiftyspiffy commented on TwitchLib.Api.Helix/EventSub.cs
> +            if (request.ShardCount is <= 0 or > 20_0000)
good catch

2024-04-02 12:16 UTC, Mahsaap approved these changes
Didn't even see that shard number in the docs. Good catch.

2024-04-02 13:52 UTC, merged