Add conduit subscription support
TwitchLib/TwitchLib.Api pull request #393
Opened 2024-05-23 14:17 UTC by FaeyUmbrea

This PR should be all the required changes to allow creating EventSub subscriptions that use the new conduit transport.

2024-05-27 22:47 UTC, swiftyspiffy approved these changes
lgtm

2024-05-27 22:53 UTC, Syzuna requested changes

2024-05-27 22:53 UTC, Syzuna commented on TwitchLib.Api.Helix/EventSub.cs
> +                    var websocketBody = new
the variable name has to be changed to sth else to avoid naming conflicts

2024-05-27 22:53 UTC, swiftyspiffy requested changes
looks like build is failing, can you look into that

2024-05-27 23:00 UTC, FaeyUmbrea commented
Seems to build now, at least locally

2024-05-27 23:13 UTC, Syzuna approved these changes
LGTM

2024-06-09 09:24 UTC, swiftyspiffy approved these changes

2024-06-09 09:25 UTC, merged